"""Make an ``Orthography`` block for a phoneme inventory (plan P10 "make-ortho"; design §13
entry 168).

Given X-SAMPA phones (diacritics allowed, e.g. ``k_w`` or ``a:``), ``make_ortho`` looks up
their bundles in the standard library ``lib:ipa.yasc`` and writes an orthography in the
additive style of spec §5.6: one line per group of phones that share values, e.g.
``[p t k] {-Voice ...}``.

- By default every library feature a phone specifies is kept, and the block is meant to follow
  ``!include "lib:ipa.yasc"`` (the library phonology is then the active one).
- With ``--minimal`` only the features chosen by :func:`yasc.tools.minimize.minimize` are
  kept, and a matching ``Phonology`` block (with the library's geometry, pruned) comes first, so
  the output is a standalone script fragment.
- ``--ipa`` writes the graphemes in IPA instead of X-SAMPA.

Command line::

    python3 -m yasc.tools.make_ortho PHONE ... [--minimal] [--force F ...] [--ipa] [--name NAME]

Exit status: 0 on success, 1 when the library does not load, 2 on a usage error.
"""

import argparse
import sys
from typing import Dict, List, Optional, Sequence, Tuple

from ..errors import YascError
from .minimize import candidates, load, minimize, phones_of, spec_item

__all__ = ["make_ortho", "phonology_block", "main"]


def phonology_block(fs, names: Sequence[str], var: Optional[str] = "P") -> str:
    """A ``Phonology`` block declaring the leaf features ``names`` of ``fs`` with their types,
    and the library's Node geometry restricted to them (spec §4.1, §4.3)."""
    keep = {fs.get(n).index for n in names}

    def wanted(f) -> bool:
        return f.index in keep or (f.is_node and any(d in keep for d in f.descendants))

    lines = []
    for f in fs.features:
        if not wanted(f):
            continue
        if f.is_node:
            lines.append("  %s Node(%s)" % (f.name, " ".join(c.name for c in f.children if wanted(c))))
        else:
            lines.append("  %s %s" % (f.name, f.type.canonical()))
    head = "$%s := Phonology [[" % var if var else "Phonology [["
    return "\n".join([head] + lines + ["]]"]) + "\n"


def make_ortho(texts: Sequence[str], *, minimal: bool = False, forced: Sequence[str] = (),
               ipa: bool = False, name: Optional[str] = None, compiled=None) -> str:
    """The script text for the X-SAMPA phones ``texts`` (plan P10; spec §5.6; design §13
    entry 168). Raises ``ValueError`` for a phone that is not one segment, or for an unusable
    forced feature."""
    compiled = compiled or load("lib:ipa.yasc")
    xs, ip = compiled.orthographies["XSAMPA"], compiled.orthographies["IPA"]
    phones = phones_of(xs, texts)
    fs = compiled.phonology
    if minimal:
        res = minimize(phones, forced, predict=False)
        feats = [fs.get(n) for n in res.features]
        feats.sort(key=lambda f: f.index)
    else:
        feats = [f for f in candidates(fs) if any(s.values[f.index] is not None for _, s in phones)]
    graphemes = [ip.render(xs.parse(t)) if ipa else t for t, _ in phones]
    # One line per feature value, then merge the lines that list the same phones.
    groups: Dict[Tuple[str, ...], List[str]] = {}
    for f in feats:
        for v in f.type.values:
            members = tuple(g for g, (_, s) in zip(graphemes, phones) if s.values[f.index] == v)
            if members:
                groups.setdefault(members, []).append(spec_item(f, v))
    seen: Dict[object, str] = {}
    clashes = []
    for g, (_, s) in zip(graphemes, phones):
        key = tuple(s.values[f.index] for f in feats)
        if key in seen:
            clashes.append("%s = %s" % (seen[key], g))
        seen.setdefault(key, g)
    out = ["%% generated by yasc.tools.make_ortho from: " + " ".join(texts)]
    if minimal:
        out.append("%% minimal features: " + " ".join(f.name for f in feats))
        out.append(phonology_block(fs, [f.name for f in feats]).rstrip("\n"))
    else:
        out.append('%% library bundles: use after  !include "lib:ipa.yasc"')
    if clashes:
        out.append("%% not distinguished (identical bundles): " + "; ".join(clashes))
    out.append(("$%s := Orthography [[" % name) if name else "Orthography [[")
    width = max(len(" ".join(m)) for m in groups) + 2 if groups else 0
    for members, specs in groups.items():
        out.append("  %-*s {%s}" % (width, "[%s]" % " ".join(members), " ".join(specs)))
    out.append("]]")
    return "\n".join(out) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> int:
    """``python3 -m yasc.tools.make_ortho`` (plan P10); returns the exit status."""
    ap = argparse.ArgumentParser(prog="python3 -m yasc.tools.make_ortho",
                                 description="Write an Orthography block for X-SAMPA phones, "
                                             "using the feature bundles of lib:ipa.yasc.")
    ap.add_argument("phones", nargs="+", metavar="PHONE", help="X-SAMPA phones (quoted lists are split)")
    ap.add_argument("--minimal", action="store_true",
                    help="keep only a minimal distinguishing feature set, with its Phonology")
    ap.add_argument("--force", nargs="+", default=[], metavar="F", help="features --minimal must keep")
    ap.add_argument("--ipa", action="store_true", help="write IPA graphemes instead of X-SAMPA")
    ap.add_argument("--name", metavar="NAME", help="assign the block to $NAME")
    try:
        args = ap.parse_args(argv)
    except SystemExit as e:
        return 0 if not e.code else 2
    texts = [t for arg in args.phones for t in arg.split()]
    try:
        compiled = load("lib:ipa.yasc")
    except (YascError, OSError) as e:
        sys.stderr.write("%s\n" % e)
        return 1
    try:
        text = make_ortho(texts, minimal=args.minimal, forced=args.force, ipa=args.ipa,
                          name=args.name, compiled=compiled)
    except ValueError as e:
        sys.stderr.write("error: %s\n" % e)
        return 2
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
